# CircleCI configuration file

version: 2.1

jobs:
  saluda:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo hola

  despedida:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo pre adios
      - run: echo adios
      - run: echo post adios      

workflows:  
  hello:
    jobs:
      - saluda   
      - despedida   